webproject/web/urls.py
from django.urls import path
from .import views
app_name='web'

urlpatterns = [
	path('',views.index,name = 'index'),
	path('category0',views.category0,name='category0'),
	path('category1',views.category1,name='category1'),
	path('category2',views.category2,name='category2'),
	path('category3',views.category3,name='category3'),
	path('post0/<int:post_id>',views.post0,name='post0'),
	path('post1/<int:post_id>',views.post1,name='post1'),
	path('post2/<int:post_id>',views.post2,name='post2'),
	path('post3/<int:post_id>',views.post3,name='post3'),
]

webproject/webproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls')),
]

webproject/web/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category0(models.Model):
	title = models.CharField(max_length = 70)
	#文章标题，字符型数据，长度70
	body = models.TextField()
	#文章主体，用TextField来存储大文本
	def get_absolute_url(self):
		return reverse('web:post0',kwargs={'post_id':self.pk})#用于返回文章编码，导入了reverse函数

class Category1(models.Model):
	title = models.CharField(max_length = 70)
	#文章标题，字符型数据，长度70
	body = models.TextField()
	#文章主体，用TextField来存储大文本
	def get_absolute_url(self):
		return reverse('web:post1',kwargs={'post_id':self.pk})#用于返回文章编码，导入了reverse函数

class Category2(models.Model):
	title = models.CharField(max_length = 70)
	#文章标题，字符型数据，长度70
	body = models.TextField()
	#文章主体，用TextField来存储大文本
	def get_absolute_url(self):
		return reverse('web:post2',kwargs={'post_id':self.pk})#用于返回文章编码，导入了reverse函数

class Category3(models.Model):
	title = models.CharField(max_length = 70)
	#文章标题，字符型数据，长度70
	body = models.TextField()
	#文章主体，用TextField来存储大文本
	def get_absolute_url(self):
		return reverse('web:post3',kwargs={'post_id':self.pk})#用于返回文章编码，导入了reverse函数
		

webproject/web/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category0,Category1,Category2,Category3
import markdown
# Create your views here.

def index(request):
	return render(request,'web/index.html')


def category0(request):
	category_list=Category0.objects.all()
	return render(request,'web/category.html',{'category_list':category_list})

def category1(request):
	category_list=Category1.objects.all()
	return render(request,'web/category.html',{'category_list':category_list})

def category2(request):
	category_list=Category2.objects.all()
	return render(request,'web/category.html',{'category_list':category_list})

def category3(request):
	category_list=Category3.objects.all()
	return render(request,'web/category.html',{'category_list':category_list})

def post0(request,post_id):
	post = get_object_or_404(Category0,pk=post_id)
	post.body = markdown.markdown(post.body,extensions=[
												'markdown.extensions.extra',
												'markdown.extensions.codehilite',
												'markdown.extensions.toc',
												])
	return render(request,'web/post.html',{'post':post})

def post1(request,post_id):
	post = get_object_or_404(Category1,pk=post_id)
	post.body = markdown.markdown(post.body,extensions=[
												'markdown.extensions.extra',
												'markdown.extensions.codehilite',
												'markdown.extensions.toc',
												])
	return render(request,'web/post.html',{'post':post})

def post2(request,post_id):
	post = get_object_or_404(Category2,pk=post_id)
	post.body = markdown.markdown(post.body,extensions=[
												'markdown.extensions.extra',
												'markdown.extensions.codehilite',
												'markdown.extensions.toc',
												])
	return render(request,'web/post.html',{'post':post})


def post3(request,post_id):
	post = get_object_or_404(Category3,pk=post_id)
	post.body = markdown.markdown(post.body,extensions=[
												'markdown.extensions.extra',
												'markdown.extensions.codehilite',
												'markdown.extensions.toc',
												])
	return render(request,'web/post.html',{'post':post})

webproject/web/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Martin</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="{% static 'web/css/style.css' %}">
	<!-- 内容展示 -->
	<link rel="stylesheet" type="text/css" href="{% static 'web/css/font-awesome.css' %}">
	<!-- 内容展示 -->
	<style type="text/css">
		a:visited{color:#000000;}  
	</style>
</head>
<body>
	<!-- 主题栏 -->
	<div class="divTop"></div>
	<!-- 主题栏 -->
	<!-- 导航栏 -->
	<div class="divNavigation">
			<li class="liNavigation"><a href="{% url 'web:index' %}" class="aNavigation">首页</a></li>
			<li class="liNavigation"><a href="{% url 'web:category0' %}" class="aNavigation">七十华诞</a></li>
			<li class="liNavigation"><a href="{% url 'web:category1' %}" class="aNavigation">风华正茂</a></li>
			<li class="liNavigation"><a href="{% url 'web:category2' %}" class="aNavigation">广工学子</a></li>
			<li class="liNavigation"><a href="{% url 'web:category3' %}" class="aNavigation">创新活动</a></li>
	</div>
	<!-- 导航栏 -->
{% block main %}
{% endblock main %}

	<!-- 返回顶部 -->	
	<button class="gototop"><span>返回顶部</span></button>
	<script src="{% static 'web/js/jquery-1.11.0.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'web/js/jquery.gototop.min.js' %}"></script>
	<script type="text/javascript">
		$(function(){
				// $(".gototop").gototop();
				$(".gototop").gototop({
					position : 0,
					duration : 1250,
					visibleAt : 300,
					classname : "isvisible"
				});
			});
	</script>
	<!-- 返回顶部 -->

</body>
</html>

webproject/web/templates/web/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
	<div class="spiritcontian">
		<div style="padding: 40px;">
		<span>当前位置：<a href="/">首页</a>&gt;<a href="#">当前位置</a></span>
		{% for categorypost in category_list %}
		<article style="border-bottom: 2px solid #c91c1c;margin-top: 25px;" class="post post-{{post.pk}}">
			<a style="font-size: 22px;text-decoration: none;" href="{{ categorypost.get_absolute_url }}">{{ categorypost.title }}</a>
		</article>
		{% endfor %}
		</div>
	</div>
	<!-- 正文区 -->
{% endblock main %}

webproject/web/templates/web/category1.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
	<div class="spiritcontian">
		<span>当前位置：<a href="#">首页</a>&gt;<a href="#">当前位置</a></span>
		<div style="word-wrap:break-word;padding: 10px 25px;"></div>
		{% for categorypost in category_list %}
			<div>{{ categorypost.title }}</div>
		{% endfor %}
	</div>
	<!-- 正文区 -->
{% endblock main %}

webproject/web/templates/web/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
	<!-- 图片展示 -->
	<div class="container-p">
		<div class="box-p"><img src="{% static 'web/img/1.jpeg' %}"><span>天安门</span></div>
		<div class="box-p"><img src="{% static 'web/img/2.jpg' %}"><span>c919首飞</span></div>
		<div class="box-p"><img src="{% static 'web/img/3.jpg' %}"><span>和谐号</span></div>
		<div class="box-p"><img src="{% static 'web/img/4.png' %}"><span>广工图书馆</span></div>
	</div>
	<!-- 图片展示 -->

	<!-- 内容展示区 -->
	<div id="body-div">
	<!-- 分类一 -->
	<div class="body-container-p">
		<a href="{% url 'web:category0' %}" class="acatalogue"><span class="spancatalogue">七十华诞</span></a>
	</div>
	<div class="body-container-p">
		<li class="box-picture">
			<img src="{% static 'web/img/1.1.jpg' %}">
			<div class="box-picture-content">
					<a href="post0/1" class="title" style="color: white">新中国创建历史</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/1.2.png' %}">
			<div class="box-picture-content">
					<a href="post0/2" class="title">看看2019哪些大事与你有关</a>	
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/1.3.png' %}">
			<div class="box-picture-content">
					<a href="post0/3" class="title">告台湾同胞书</a>
			</div>
		</li>
	</div>
	<div class="body-container-p">
		<li class="box-picture">
			<img src="{% static 'web/img/1.4.jpg' %}">
			<div class="box-picture-content">
					<a href="post0/4" class="title">不忘初心</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/1.5.jpeg' %}">
			<div class="box-picture-content">
					<a href="post0/5" class="title">我们都是追梦人</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/1.6.png' %}">
			<div class="box-picture-content">
					<a href="post0/6" class="title">人类命运共同体</a>
			</div>
		</li>
	</div>
	<!-- 分类一 -->
	<!-- 分类二 -->
	<div class="body-container-p">
		<a href="{% url 'web:category1' %}" class="acatalogue"><span class="spancatalogue">风华正茂</span></a>
	</div>
	<div class="body-container-p">
		<div id="wrapper" style="display: inline-block">
			<div id="slider-wrap">
			  <ul id="slider">
				 <li>
					<img src="{% static 'web/img/2.1.jpg' %}">
					<div>
						<h3>国务院部署全面加强基础科研</h3>
					</div>                
				 </li>

				 <li>
					<img src="{% static 'web/img/2.2.jpg' %}">
					<div>
						<h3>散裂中子源投入运行</h3>
					</div>
				 </li>

				 <li>
					<img src="{% static 'web/img/2.3.jpg' %}">
					<div>
						<h3>首只体细胞克隆猴</h3>
					</div>
				 </li>

				 <li>
					<img src="{% static 'web/img/2.4.jpg' %}">
					<div>
						<h3>首次人工创建单染色体</h3>
					</div>
				 </li>
			  </ul>
			   <!--controls-->
			  <div class="btns" id="next"><i class="fa fa-arrow-right"></i></div>
			  <div class="btns" id="previous"><i class="fa fa-arrow-left"></i></div>
			  <div id="counter"></div>

			  <div id="pagination-wrap">
				<ul>
				</ul>
	  </div>
	  <!--controls-->  
			 
	</div>
</div>
	 	<script src="{% static 'web/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'web/js/slide.js' %}"></script>
		<div id="catalogue-two">
			<div class="catalogue-two-one"><a class="catalogue-two-one" href="post1/1">港珠澳大桥、北斗三号 数说2018经济发展重大成就</a></div>
			<div class="catalogue-two-one"><a class="catalogue-two-one" href="post1/2">回望2018：哪些科技成就值得点赞</a></div>
			<div class="catalogue-two-one"><a class="catalogue-two-one" href="post1/3">外媒惊叹中国高铁取得成就</a></div>
			<!-- 
			<a class="catalogue-two-one" href="#">港珠澳大桥、北斗三号 数说2018经济发展重大成就</a>
			<a class="catalogue-two-one" href="#">回望2018：哪些科技成就值得点赞</a>
			<a class="catalogue-two-one" href="#">外媒惊叹中国高铁取得成就：全球中国称第二 没人敢说第一</a>
		-->
		</div>	
	</div>
	<!-- 分类二 -->
<!-- 分类三 -->
	<div class="body-container-p">
		<a href="{% url 'web:category2' %}" class="acatalogue"><span class="spancatalogue">广工学子</span></a>
	</div>
	<div class="body-container-p">
		<div class="catalogue-three">
			<a href="post2/1">广东工业大学简介</a>
			<span></span><div style="word-wrap:break-word;">广东工业大学由原广东工学院、广东机械学院和华南建设学院（东院）于1995年6月合并组建而成。学校已有60年的办学历史，是一所以工为主、工理经管文法艺结合、多科性协调发展的省属重点大学，是广东省高水平大学重点建设高校。</div>
			<div></div>
		</div>
		<div class="catalogue-three">
			<a href="post2/2">广工学子登上央视春晚舞台</a>
			<span></span>
			<!-- word-wrap:break-word 强制换行-->
			<div style="word-wrap:break-word;">在央视2018春晚珠海分会场上，广工学子登上春晚舞台，为全国人民送上精彩表演。他们与南方歌舞团、星海音乐学院舞蹈学院、广东舞蹈戏剧学院等专业舞蹈演员一起，出演了分会场直播连线的主体节目——歌曲《勇气》，用自己的演绎向全国人民拜年。</div>
			<div></div>
		</div>
		<div class="catalogue-three">
			<a href="post2/3">“力行公益，we are ready”</a>
			<span></span>
			<div style="word-wrap:break-word;"> 2019年3月23日，我院红会协助广州血液中心在学校教六天桥下组织全血捐献活动。献血活动的开展，带动广大热心公益的同学积极参与到社会救助中，发扬大学生无私奉献的精神。</div>
		</div>
	</div>
	<!-- 分类三 -->
	<!-- 分类四 -->
	<div class="body-container-p">
		<a href="{% url 'web:category3' %}" class="acatalogue"><span class="spancatalogue">创新活动</span></a>
	</div>
	<div class="body-container-p">
		<li class="box-picture">
			<img src="{% static 'web/img/4.1.jpg' %}">
			<div class="box-picture-content">
				<a href="post3/1" class="title">广工QG团队</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/4.2.jpg' %}">
			<div class="box-picture-content">
				<a href="post3/2" class="title">中国高校计算机大赛我校学子获金奖</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/4.3.jpg' %}">
			<div class="box-picture-content">
				<a href="post3/3" class="title">乐鱼科技教育团队</a>
			</div>
		</li>
	</div>
	<div class="body-container-p">
		<li class="box-picture">
			<img src="{% static 'web/img/4.4.jpg' %}">
			<div class="box-picture-content">
				<a href="post3/4" class="title">机器人创新团队</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/4.5.png' %}">
			<div class="box-picture-content">
				<a href="post3/5" class="title">机器人集成中心</a>
			</div>
		</li>
		<li class="box-picture">
			<img src="{% static 'web/img/4.6.jpg' %}">
			<div class="box-picture-content">
				<a href="post3/6" class="title">创新创业导师面对面</a>
			</div>
		</li>
	</div>
	<!-- 分类四 -->
	</div>
{% endblock main %}

webproject/web/templates/web/post.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block main %}
	<!-- 正文区 -->
	<div class="spiritcontian">
		<div style="padding: 40px;">
		<span>当前位置：<a href="/">首页</a>&gt;<a href="javascript:history.back();">{{ post.category }}</a>&gt;<a href="#">当前位置</a></span>
		<div class="headline">
			{{ post.title }}
		</div>
		<div style="padding: 40px;font-size: 18px;">
			{{ post.body|safe }}
		</div>
{% endblock main %}